use crate::board::{PropertyLevel, Tile};
use lazy_static::lazy_static;

lazy_static! {
    pub static ref MAP1: Vec<Tile> = vec![
        Tile::Go { amount: 200 },
        Tile::Tax { price: 200 },
        Tile::Chance("Community Chest".to_string()),
        Tile::Tax { price: 200 },
        Tile::Tax { price: 200 },
        Tile::Tax { price: 200 },
        Tile::Tax { price: 200 },
        Tile::Chance("Chance".to_string()),
        Tile::Tax { price: 200 },
        Tile::Tax { price: 200 },
        Tile::Jail,
        Tile::Tax { price: 200 },
        Tile::Utility {
            cost: 150,
            owner: None,
        },
        Tile::Property {
            name: "States Avenue".to_string(),
            costs: vec![140],
            rents: vec![10, 50, 150, 450, 625, 750],
            level: PropertyLevel::None,
            owner: None,
        },
        Tile::Property {
            name: "Virginia Avenue".to_string(),
            costs: vec![160],
            rents: vec![12, 60, 180, 500, 700, 900],
            level: PropertyLevel::None,
            owner: None,
        },
        Tile::Railroad {
            owner: None,
            cost: 200,
            rents: vec![25, 50, 100, 200],
        },
        Tile::Property {
            name: "St. James Place".to_string(),
            costs: vec![180],
            rents: vec![14, 70, 200, 550, 750, 950],
            level: PropertyLevel::None,
            owner: None,
        },
        Tile::Chance("Community Chest".to_string()),
        Tile::Property {
            name: "Tennessee Avenue".to_string(),
            costs: vec![180],
            rents: vec![14, 70, 200, 550, 750, 950],
            level: PropertyLevel::None,
            owner: None,
        },
        Tile::Property {
            name: "New York Avenue".to_string(),
            costs: vec![200],
            rents: vec![16, 80, 220, 600, 800, 1000],
            level: PropertyLevel::None,
            owner: None,
        },
        Tile::FreeParking,
        Tile::Property {
            name: "Kentucky Avenue".to_string(),
            costs: vec![220],
            rents: vec![18, 90, 250, 700, 875, 1050],
            level: PropertyLevel::None,
            owner: None,
        },
        Tile::Chance("Community Chest".to_string()),
        Tile::Property {
            name: "Indiana Avenue".to_string(),
            costs: vec![220],
            rents: vec![18, 90, 250, 700, 875, 1050],
            level: PropertyLevel::None,
            owner: None,
        },
        Tile::Property {
            name: "Illinois Avenue".to_string(),
            costs: vec![240],
            rents: vec![20, 100, 300, 750, 925, 1100],
            level: PropertyLevel::None,
            owner: None,
        },
        Tile::Railroad {
            owner: None,
            cost: 200,
            rents: vec![25, 50, 100, 200],
        },
        Tile::Property {
            name: "Atlantic Avenue".to_string(),
            costs: vec![260],
            rents: vec![22, 110, 330, 800, 975, 1150],
            level: PropertyLevel::None,
            owner: None,
        },
        Tile::Property {
            name: "Ventnor Avenue".to_string(),
            costs: vec![260],
            rents: vec![22, 110, 330, 800, 975, 1150],
            level: PropertyLevel::None,
            owner: None,
        },
        Tile::Utility {
            cost: 150,
            owner: None
        },
        Tile::Property {
            name: "Marvin Gardens".to_string(),
            costs: vec![280],
            rents: vec![24, 120, 360, 850, 1025, 1200],
            level: PropertyLevel::None,
            owner: None,
        },
        Tile::GoToJail,
        Tile::Property {
            name: "Pacific Avenue".to_string(),
            costs: vec![300],
            rents: vec![26, 130, 390, 900, 1100, 1275],
            level: PropertyLevel::None,
            owner: None,
        },
        Tile::Property {
            name: "North Carolina Avenue".to_string(),
            costs: vec![300],
            rents: vec![26, 130, 390, 900, 1100, 1275],
            level: PropertyLevel::None,
            owner: None,
        },
        Tile::Chance("Community Chest".to_string()),
        Tile::Property {
            name: "Pennsylvania Avenue".to_string(),
            costs: vec![320],
            rents: vec![28, 150, 450, 1000, 1200, 1400],
            level: PropertyLevel::None,
            owner: None,
        },
        Tile::Railroad {
            owner: None,
            cost: 200,
            rents: vec![25, 50, 100, 200],
        },
        Tile::Chance("Chance".to_string()),
        Tile::Property {
            name: "Park Place".to_string(),
            costs: vec![350],
            rents: vec![35, 175, 500, 1100, 1300, 1500],
            level: PropertyLevel::None,
            owner: None,
        },
        Tile::LuxuryTax { price: 100 },
        Tile::Property {
            name: "Boardwalk".to_string(),
            costs: vec![400],
            rents: vec![50, 200, 600, 1400, 1700, 2000],
            level: PropertyLevel::None,
            owner: None,
        },
    ];
}
